# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: modu

before:
  hooks:
  # You may remove this if you don't use go modules.
  - go mod tidy -v
  # you may remove this if you don't need go generate
  - go generate ./...

upx:
# Whether to enable it or not.
#
# Templates: allowed.
- enabled: true
  compress: best

builds:
- binary: modu
  main: ./main.go
  goos:
  - windows
  - darwin
  - linux
  - freebsd
  goarch:
  - '386'
  - amd64
  - arm
  - arm64
  - riscv64
  goarm:
  - '6'
  ignore:
  - goos: darwin
    goarch: '386'
  - goos: darwin
    goarch: riscv64
  - goos: windows
    goarch: riscv64
  env:
  - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
  - -trimpath
  ldflags:
  - -s -w # Don't set main.version.

gomod:
  proxy: true

archives:
- name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
  files:
  - README.md
  - LICENSE
  format_overrides:
  - goos: windows
    formats: [ zip ]

release:
  draft: true
  replace_existing_draft: true
  replace_existing_artifacts: true
  target_commitish: "{{ .Commit }}"
  prerelease: auto
  make_latest: true
  mode: append
  include_meta: true

snapshot:
  version_template: "{{.Version}}"

checksum:
  name_template: "task_checksums.txt"

sboms:
- id: modu
  documents:
  - "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.sbom.json"
  cmd: syft
  args: [ "$artifact", "--output", "cyclonedx-json=$document" ]
  artifacts: binary
  ids:
  - modu

# Whether to enable the size reporting or not.
report_sizes: true
