# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
- binary: task
  main: main.go
  goos:
  - windows
  - darwin
  - linux
  - freebsd
  goarch:
  - '386'
  - amd64
  - arm
  - arm64
  - riscv64
  goarm:
  - '6'
  ignore:
  - goos: darwin
    goarch: '386'
  - goos: darwin
    goarch: riscv64
  - goos: windows
    goarch: riscv64
  env:
  - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
  - -trimpath
  ldflags:
  - -s -w # Don't set main.version.

gomod:
  proxy: true

archives:
- name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
  files:
  - README.md
  - LICENSE
  format_overrides:
  - goos: windows
    formats: [ zip ]

release:
  draft: true

snapshot:
  version_template: "{{.Version}}"

checksum:
  name_template: "task_checksums.txt"
